const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'src', 'lib', 'i18n.ts');
let content = fs.readFileSync(filePath, 'utf8');

const translations = {
  da: {
    navAdd: "download: 'Download App', light: 'Lyst', dark: 'Mørkt'",
    commonNew: "error: 'Fejl', ready: 'Klar', failed: 'Mislykkedes', saving: 'Gemmer...', score: 'Score', user: 'Bruger'",
    footer: "desc: 'Forvandl dine lange videoer til fængende korte klip med AI-drevet analyse og redigering.', quickLinks: 'Hurtige Links', legal: 'Juridisk', privacy: 'Privatlivspolitik', terms: 'Servicevilkår', contact: 'Kontakt', rights: 'Alle rettigheder forbeholdes.'",
    heroBadge: "badge: 'AI-drevet Videobehandling',",
    howItWorks: "howItWorks: { title: 'Sådan Virker Det', step1: { title: 'Indsæt Video', desc: 'Indsæt URL eller upload din video' }, step2: { title: 'AI-analyse', desc: 'AI registrerer automatisk højdepunkter' }, step3: { title: 'Opret Klip', desc: 'Korte videoer oprettes' }, step4: { title: 'Download', desc: 'Eksporter og del overalt' } },",
    videoNew: "creditsAvailable: 'kredit tilgængelig', signInToStart: 'for at starte videobehandling', pasteUrlPlaceholder: 'Indsæt en video-URL (MP4, MOV, AVI...)', useLocalAgent: 'Brug lokal Mac Agent (anbefalet til stabil YouTube)', uploadLocal: 'Upload en lokal videofil (anbefalet når YouTube-link er blokeret)', selectedFile: 'Valgt', downloadMacApp: 'Download Mac App', viewPricing: 'Se Priser', clipsReady: 'klip klar', playableClips: 'afspilbare klip', failedClips: 'mislykkedes', aiFinished: 'AI har afsluttet udvælgelsen af de stærkeste øjeblikke fra din kildevideo.', openToPreview: 'Åbn ethvert klar klip for at forhåndsvise det inline, eller download MP4 direkte.', clipsBeingGenerated: 'Klip genereres:', videoPreviewNotAvailable: 'Videoforhåndsvisning ikke tilgængelig', clipMayStillProcessing: 'Klippen behandles muligvis stadig eller kunne ikke genereres.', insufficientCredits: 'Utilstrækkelige kreditter. Du skal bruge mindst 30 kreditter.', enterVideoUrl: 'Indtast venligst en video-URL eller upload en lokal videofil.', enterValidUrl: 'Indtast venligst en gyldig offentlig http(s) video-URL.'",
    videoStage: "stage: { init: 'Initialiserer...', extractFrames: 'Udtrækker videobilleder...', framesExtracted: 'Billeder udtrukket succesfuldt', framesUnavailable: 'Fortsætter med analyse', aiAnalysis: 'AI analyserer videoindhold...', analysisComplete: 'Analyse fuldført', generatingClip: 'Opretter højdepunktsklip...', clipReady: 'Højdepunktsklip klar', saving: 'Gemmer resultater...', complete: 'Behandling fuldført!', error: 'Fejl opstod' },",
    pricingNew: "paymentNote: 'Alipay for Kina · Creem for International (Visa / Mastercard / Apple Pay / Google Pay)', secureNote: 'Alle betalinger sikret med TLS 256-bit kryptering', faqTitle: 'Ofte Stillede Spørgsmål', faq: { q1: 'Hvad er en kredit?', a1: 'Hver kredit repræsenterer behandlingskraft. Behandling af et videoklip koster 30 kreditter.', q2: 'Hvordan fungerer daglig kredit-nulstilling?', a2: 'Kreditter nulstilles til din plans daglige grænse kl. 00:00 UTC hver dag. Ubrugte kreditter overføres ikke.', q3: 'Kan jeg opgradere eller nedgradere min plan?', a3: 'Ja, du kan ændre din plan når som helst. Ændringer træder i kraft straks.', q4: 'Hvilke videokilder understøttes?', a4: 'Vi understøtter YouTube, Bilibili og direkte videofil-upload (MP4, MOV, AVI).', q5: 'Hvilke betalingsmetoder understøttes?', a5: 'Alipay for Kina-brugere, Creem (Visa, Mastercard, Apple Pay, Google Pay) for internationale brugere.' }, mostPopular: 'Mest Populære'",
    downloadPage: "downloadPage: { title: 'Download Clipop Agent', subtitle: 'Skrivebordsapp til stabil YouTube/Bilibili videobehandling', badge: 'Skrivebordsapp', macTitle: 'macOS', macDesc: 'Til Apple Silicon (M1/M2/M3/M4) Macs', downloadButton: 'Download til macOS', version: 'Version', fileSize: 'Filstørrelse', requirements: 'macOS 12.0 eller senere', installing: 'Installationsvejledning', step1: 'Klik på download-knappen for at gemme .dmg-filen', step2: 'Dobbeltklik på den downloadede .dmg-fil', step3: 'Træk Clipop Agent til Applications-mappen', step4: 'Åbn Clipop Agent fra Applications', notAvailable: 'Download forberedes, tjek venligst senere', backToHome: 'Tilbage til Forsiden', whyDesktopTitle: 'Hvorfor Bruge Skrivebordsappen?', features: { stable: { title: 'Stabil Behandling', desc: 'Behandl videoer lokalt med maksimal stabilitet' }, fast: { title: 'Hurtig Download', desc: 'Download videoer direkte uden browserbegrænsninger' }, local: { title: 'Lokal Behandling', desc: 'Behandl videoer på din Mac for privatliv og hastighed' } } },",
    loginNew: "successTitle: 'Login Lykkedes!', successMessage: 'Du er logget ind som', successDesktopHint: 'Klik på knappen herunder for at vende tilbage til skrivebordsappen.', returnToDesktop: 'Vend tilbage til Clipop Agent', desktopNotOpened: 'Hvis skrivebordsappen ikke åbner automatisk, skal du sikre dig, at Clipop Agent kører.'",
    registerNew: "errorNameRequired: 'Indtast venligst dit navn', errorEmailRequired: 'Indtast venligst din e-mail', errorPasswordLength: 'Adgangskoden skal være mindst 6 tegn', errorPasswordMismatch: 'Adgangskoder matcher ikke', errorEmailExists: 'Denne e-mail er allerede registreret. Log venligst ind.', errorSendCode: 'Kunne ikke sende kode', errorNetwork: 'Netværksfejl. Prøv venligst igen.', errorCodeLength: 'Indtast venligst 6-cifret kode', successTitle: 'Konto Oprettet!', successMessage: 'Din konto er oprettet som', successDesktopHint: 'Klik på knappen herunder for at vende tilbage til skrivebordsappen.', returnToDesktop: 'Vend tilbage til Clipop Agent', desktopNotOpened: 'Hvis skrivebordsappen ikke åbner automatisk, skal du sikre dig, at Clipop Agent kører.'",
    dashboardNew: "untitled: 'Unavngivet', clip: 'Klip', clipsCount: 'højdepunkter', clipsHint: 'Klik på et klip for at afspille', desktopLoginDetected: 'Skrivebordsapp-login Registreret', desktopLoginHint: 'Klik på knappen herunder for at vende tilbage til Clipop Agent', returnToDesktop: 'Vend tilbage til Clipop Agent', welcomeBack: 'Velkommen tilbage', videosProcessed: 'Behandlede Videoer', videosProcessedDesc: 'Total behandlede videoer', clipsGenerated: 'Genererede Klip', clipsGeneratedDesc: 'Total højdepunktsklip', currentPlan: 'Nuværende Plan', upgradePlan: 'Opgrader Plan', processNewVideo: 'Behandl Ny Video', feedback: 'Feedback', historyHint: 'Klik på fulførte poster for at udvide og se højdepunktsklip', processNewVideoDesc: 'Gå til forsiden for at behandle en ny lang video', goToProcessor: 'Gå til Videoprocessor', userFeedback: 'Brugerfeedback', feedbackDesc: 'Fortæl os om funktioner du vil forbedre eller problemer du har stødt på', feedbackPlaceholder: 'Indtast din feedback (forslag, fejl, funktionsanmodninger osv.)', feedbackSubmitted: 'Indsendt, tak for din feedback!', submitFeedback: 'Indsend Feedback', feedbackFailed: 'Kunne ikke indsende feedback', statusPending: 'Afventer', statusProcessing: 'Behandler', statusCompleted: '✓ Fuldført', statusFailed: 'Mislykkedes'",
    blogNew: "subtitle: 'Seneste nyheder, tips og opdateringer fra Clipop AI', views: 'visninger'",
  },
  fi: {
    navAdd: "download: 'Lataa Sovellus', light: 'Vaalea', dark: 'Tumma'",
    commonNew: "error: 'Virhe', ready: 'Valmis', failed: 'Epäonnistui', saving: 'Tallentaa...', score: 'Pisteet', user: 'Käyttäjä'",
    footer: "desc: 'Muuta pitkät videosi kiehtoviksi lyhyiksi klipseiksi tekoälypohjaisella analyysillä ja editoinnilla.', quickLinks: 'Pikalinkit', legal: 'Lakiasiat', privacy: 'Tietosuojakäytäntö', terms: 'Käyttöehdot', contact: 'Yhteystiedot', rights: 'Kaikki oikeudet pidätetään.'",
    heroBadge: "badge: 'Tekoälypohjainen Videokäsittely',",
    howItWorks: "howItWorks: { title: 'Näin Se Toimii', step1: { title: 'Syötä Video', desc: 'Liitä URL tai lataa videosi' }, step2: { title: 'Tekoälyanalyysi', desc: 'Tekoäly havaitsee kohokohdat automaattisesti' }, step3: { title: 'Luo Klippejä', desc: 'Lyhyet videot luodaan' }, step4: { title: 'Lataa', desc: 'Vie ja jaa missä tahansa' } },",
    videoNew: "creditsAvailable: 'krediittiä käytettävissä', signInToStart: 'aloittaaksesi videoiden käsittelyn', pasteUrlPlaceholder: 'Liitä videon URL (MP4, MOV, AVI...)', useLocalAgent: 'Käytä paikallista Mac Agenttia (suositeltu vakaalle YouTubelle)', uploadLocal: 'Lataa paikallinen videotiedosto (suositeltu kun YouTube-linkki on estetty)', selectedFile: 'Valittu', downloadMacApp: 'Lataa Mac-sovellus', viewPricing: 'Katso Hinnat', clipsReady: 'klippiä valmiina', playableClips: 'toistettavaa klippiä', failedClips: 'epäonnistui', aiFinished: 'Tekoäly on suorittanut vahvimpien hetkien valinnan lähdevideostasi.', openToPreview: 'Avaa mikä tahansa valmis klippi esikatseluun tai lataa MP4 suoraan.', clipsBeingGenerated: 'Klippejä luodaan:', videoPreviewNotAvailable: 'Videon esikatselu ei ole saatavilla', clipMayStillProcessing: 'Klippi saattaa olla yhä käsittelyssä tai sen luominen epäonnistui.', insufficientCredits: 'Krediittejä ei riittävästi. Tarvitset vähintään 30 krediittiä.', enterVideoUrl: 'Anna videon URL tai lataa paikallinen videotiedosto.', enterValidUrl: 'Anna kelvollinen julkinen http(s) videon URL.'",
    videoStage: "stage: { init: 'Alustetaan...', extractFrames: 'Puretaan videoruutuja...', framesExtracted: 'Ruudut purettu onnistuneesti', framesUnavailable: 'Jatketaan analyysillä', aiAnalysis: 'Tekoäly analysoi videosisältöä...', analysisComplete: 'Analyysi valmis', generatingClip: 'Luodaan kohokohdaklippiä...', clipReady: 'Kohokohdaklippi valmis', saving: 'Tallennetaan tuloksia...', complete: 'Käsittely valmis!', error: 'Virhe tapahtui' },",
    pricingNew: "paymentNote: 'Alipay Kiinalle · Creem kansainvälisille (Visa / Mastercard / Apple Pay / Google Pay)', secureNote: 'Kaikki maksut suojattu TLS 256-bit salauksella', faqTitle: 'Usein Kysytyt Kysymykset', faq: { q1: 'Mikä on krediitti?', a1: 'Jokainen krediitti edustaa käsittelytehoa. Videoklipin käsittely maksaa 30 krediittiä.', q2: 'Miten päivittäinen krediittien nollaus toimii?', a2: 'Krediitit nollataan suunnitelmasi päivittäiseen rajaan joka päivä klo 00:00 UTC. Käyttämättömät krediitit eivät siirry.', q3: 'Voinko päivittää tai alentaa suunnitelmaani?', a3: 'Kyllä, voit vaihtaa suunnitelmaa milloin tahansa. Muutokset astuvat voimaan heti.', q4: 'Mitä videolähteitä tuetaan?', a4: 'Tuemme YouTubea, Bilibiliä ja suoria videotiedostojen latauksia (MP4, MOV, AVI).', q5: 'Mitä maksutapoja tuetaan?', a5: 'Alipay Kiinan käyttäjille, Creem (Visa, Mastercard, Apple Pay, Google Pay) kansainvälisille käyttäjille.' }, mostPopular: 'Suosituin'",
    downloadPage: "downloadPage: { title: 'Lataa Clipop Agent', subtitle: 'Työpöytäsovellus vakaaseen YouTube/Bilibili videokäsittelyyn', badge: 'Työpöytäsovellus', macTitle: 'macOS', macDesc: 'Apple Silicon (M1/M2/M3/M4) Mac-tietokoneille', downloadButton: 'Lataa macOS:lle', version: 'Versio', fileSize: 'Tiedostokoko', requirements: 'macOS 12.0 tai uudempi', installing: 'Asennusopas', step1: 'Klikkaa latauspainiketta tallentaaksesi .dmg-tiedoston', step2: 'Kaksoisklikkaa ladattua .dmg-tiedostoa', step3: 'Vedä Clipop Agent Sovellukset-kansioon', step4: 'Avaa Clipop Agent Sovellukset-kansiosta', notAvailable: 'Latausta valmistellaan, tarkista myöhemmin uudelleen', backToHome: 'Takaisin Etusivulle', whyDesktopTitle: 'Miksi Käyttää Työpöytäsovellusta?', features: { stable: { title: 'Vakaa Käsittely', desc: 'Käsittele videoita paikallisesti maksimaalisella vakaudella' }, fast: { title: 'Nopea Lataus', desc: 'Lataa videoita suoraan ilman selaimen rajoituksia' }, local: { title: 'Paikallinen Käsittely', desc: 'Käsittele videoita Macillasi yksityisyyden ja nopeuden vuoksi' } } },",
    loginNew: "successTitle: 'Kirjautuminen Onnistui!', successMessage: 'Olet kirjautunut sisään onnistuneesti nimellä', successDesktopHint: 'Klikkaa alla olevaa painiketta palataksesi työpöytäsovellukseen.', returnToDesktop: 'Palaa Clipop Agentiin', desktopNotOpened: 'Jos työpöytäsovellus ei avaudu automaattisesti, varmista että Clipop Agent on käynnissä.'",
    registerNew: "errorNameRequired: 'Anna nimesi', errorEmailRequired: 'Anna sähköpostiosoitteesi', errorPasswordLength: 'Salasanan on oltava vähintään 6 merkkiä', errorPasswordMismatch: 'Salasanat eivät täsmää', errorEmailExists: 'Tämä sähköpostiosoite on jo rekisteröity. Kirjaudu sisään.', errorSendCode: 'Koodin lähetys epäonnistui', errorNetwork: 'Verkkovirhe. Yritä uudelleen.', errorCodeLength: 'Anna 6-numeroinen koodi', successTitle: 'Tili Luotu!', successMessage: 'Tilisi on luotu onnistuneesti nimellä', successDesktopHint: 'Klikkaa alla olevaa painiketta palataksesi työpöytäsovellukseen.', returnToDesktop: 'Palaa Clipop Agentiin', desktopNotOpened: 'Jos työpöytäsovellus ei avaudu automaattisesti, varmista että Clipop Agent on käynnissä.'",
    dashboardNew: "untitled: 'Nimetön', clip: 'Klippi', clipsCount: 'kohokohtaa', clipsHint: 'Klikkaa mitä tahansa klippiä toistaaksesi', desktopLoginDetected: 'Työpöytäsovelluksen Kirjautuminen Havaittu', desktopLoginHint: 'Klikkaa alla olevaa painiketta palataksesi Clipop Agentiin', returnToDesktop: 'Palaa Clipop Agentiin', welcomeBack: 'Tervetuloa takaisin', videosProcessed: 'Käsitellyt Videot', videosProcessedDesc: 'Käsitellyt videot yhteensä', clipsGenerated: 'Luodut Klipit', clipsGeneratedDesc: 'Kohokohdaklipit yhteensä', currentPlan: 'Nykyinen Suunnitelma', upgradePlan: 'Päivitä Suunnitelma', processNewVideo: 'Käsittele Uusi Video', feedback: 'Palaute', historyHint: 'Klikkaa valmiita tietueita laajentaaksesi ja nähdäksesi kohokohdaklipit', processNewVideoDesc: 'Mene etusivulle käsitelläksesi uuden pitkän videon', goToProcessor: 'Mene Videoprosessoriin', userFeedback: 'Käyttäjäpalaute', feedbackDesc: 'Kerro meille ominaisuuksista joita haluat parantaa tai ongelmista joita olet kohdannut', feedbackPlaceholder: 'Anna palautettasi (ehdotukset, virheet, ominaisuuspyynnöt jne.)', feedbackSubmitted: 'Lähetetty, kiitos palautteestasi!', submitFeedback: 'Lähetä Palaute', feedbackFailed: 'Palautteen lähetys epäonnistui', statusPending: 'Odottaa', statusProcessing: 'Käsitellään', statusCompleted: '✓ Valmis', statusFailed: 'Epäonnistui'",
    blogNew: "subtitle: 'Uusimmat uutiset, vinkit ja päivitykset Clipop AI:lta', views: 'katselukertaa'",
  },
  nl: {
    navAdd: "download: 'App Downloaden', light: 'Licht', dark: 'Donker'",
    commonNew: "error: 'Fout', ready: 'Klaar', failed: 'Mislukt', saving: 'Opslaan...', score: 'Score', user: 'Gebruiker'",
    footer: "desc: 'Transformeer je lange video\'s naar boeiende korte clips met AI-aangedreven analyse en bewerking.', quickLinks: 'Snelle Links', legal: 'Juridisch', privacy: 'Privacybeleid', terms: 'Servicevoorwaarden', contact: 'Contact', rights: 'Alle rechten voorbehouden.'",
    heroBadge: "badge: 'AI-Aangedreven Videoverwerking',",
    howItWorks: "howItWorks: { title: 'Hoe Het Werkt', step1: { title: 'Video Invoeren', desc: 'Plak URL of upload je video' }, step2: { title: 'AI-analyse', desc: 'AI detecteert automatisch hoogtepunten' }, step3: { title: 'Clips Maken', desc: 'Korte video\'s worden gemaakt' }, step4: { title: 'Downloaden', desc: 'Exporteer en deel overal' } },",
    videoNew: "creditsAvailable: 'credits beschikbaar', signInToStart: 'om te beginnen met videoverwerking', pasteUrlPlaceholder: 'Plak een video-URL (MP4, MOV, AVI...)', useLocalAgent: 'Gebruik lokale Mac Agent (aanbevolen voor stabiele YouTube)', uploadLocal: 'Upload een lokale videobestand (aanbevolen wanneer YouTube-link geblokkeerd is)', selectedFile: 'Geselecteerd', downloadMacApp: 'Mac App Downloaden', viewPricing: 'Bekijk Prijzen', clipsReady: 'clips klaar', playableClips: 'afspeelbare clips', failedClips: 'mislukt', aiFinished: 'AI heeft het selecteren van de sterkste momenten uit je bronvideo voltooid.', openToPreview: 'Open een gereed clip om een voorvertoning te bekijken, of download de MP4 direct.', clipsBeingGenerated: 'Clips worden gegenereerd:', videoPreviewNotAvailable: 'Videovoorvertoning niet beschikbaar', clipMayStillProcessing: 'De clip wordt mogelijk nog verwerkt of het genereren is mislukt.', insufficientCredits: 'Onvoldoende credits. Je hebt minimaal 30 credits nodig.', enterVideoUrl: 'Voer een video-URL in of upload een lokaal videobestand.', enterValidUrl: 'Voer een geldige openbare http(s) video-URL in.'",
    videoStage: "stage: { init: 'Initialiseren...', extractFrames: 'Videoframes extraheren...', framesExtracted: 'Frames succesvol geëxtraheerd', framesUnavailable: 'Doorgaan met analyse', aiAnalysis: 'AI analyseert video-inhoud...', analysisComplete: 'Analyse voltooid', generatingClip: 'Hoogtepuntclip maken...', clipReady: 'Hoogtepuntclip klaar', saving: 'Resultaten opslaan...', complete: 'Verwerking voltooid!', error: 'Fout opgetreden' },",
    pricingNew: "paymentNote: 'Alipay voor China · Creem voor Internationaal (Visa / Mastercard / Apple Pay / Google Pay)', secureNote: 'Alle betalingen beveiligd met TLS 256-bit encryptie', faqTitle: 'Veelgestelde Vragen', faq: { q1: 'Wat is een credit?', a1: 'Elke credit vertegenwoordigt verwerkingskracht. Het verwerken van een videoclip kost 30 credits.', q2: 'Hoe werkt de dagelijkse credit-reset?', a2: 'Credits worden elke dag om 00:00 UTC gereset naar de dagelijkse limiet van je abonnement. Ongebruikte credits worden niet overgedragen.', q3: 'Kan ik mijn abonnement upgraden of downgraden?', a3: 'Ja, je kunt je abonnement op elk moment wijzigen. Wijzigingen treden onmiddellijk in werking.', q4: 'Welke videobronnen worden ondersteund?', a4: 'We ondersteunen YouTube, Bilibili en directe videobestand-uploads (MP4, MOV, AVI).', q5: 'Welke betaalmethoden worden ondersteund?', a5: 'Alipay voor China-gebruikers, Creem (Visa, Mastercard, Apple Pay, Google Pay) voor internationale gebruikers.' }, mostPopular: 'Meest Populair'",
    downloadPage: "downloadPage: { title: 'Download Clipop Agent', subtitle: 'Desktop-app voor stabiele YouTube/Bilibili videoverwerking', badge: 'Desktop-app', macTitle: 'macOS', macDesc: 'Voor Apple Silicon (M1/M2/M3/M4) Macs', downloadButton: 'Download voor macOS', version: 'Versie', fileSize: 'Bestandsgrootte', requirements: 'macOS 12.0 of later', installing: 'Installatiehandleiding', step1: 'Klik op de downloadknop om het .dmg-bestand op te slaan', step2: 'Dubbelklik op het gedownloade .dmg-bestand', step3: 'Sleep Clipop Agent naar de Applicaties-map', step4: 'Open Clipop Agent vanuit Applicaties', notAvailable: 'Download wordt voorbereid, controleer later opnieuw', backToHome: 'Terug naar Home', whyDesktopTitle: 'Waarom de Desktop-app Gebruiken?', features: { stable: { title: 'Stabiele Verwerking', desc: 'Verwerk video\'s lokaal met maximale stabiliteit' }, fast: { title: 'Snelle Download', desc: 'Download video\'s direct zonder browserbeperkingen' }, local: { title: 'Lokale Verwerking', desc: 'Verwerk video\'s op je Mac voor privacy en snelheid' } } },",
    loginNew: "successTitle: 'Inloggen Succesvol!', successMessage: 'Je bent succesvol ingelogd als', successDesktopHint: 'Klik op de onderstaande knop om terug te keren naar de desktop-app.', returnToDesktop: 'Terug naar Clipop Agent', desktopNotOpened: 'Als de desktop-app niet automatisch opent, zorg er dan voor dat Clipop Agent draait.'",
    registerNew: "errorNameRequired: 'Voer je naam in', errorEmailRequired: 'Voer je e-mailadres in', errorPasswordLength: 'Wachtwoord moet minimaal 6 tekens bevatten', errorPasswordMismatch: 'Wachtwoorden komen niet overeen', errorEmailExists: 'Dit e-mailadres is al geregistreerd. Log in plaats daarvan in.', errorSendCode: 'Code verzenden mislukt', errorNetwork: 'Netwerkfout. Probeer opnieuw.', errorCodeLength: 'Voer een 6-cijferige code in', successTitle: 'Account Aangemaakt!', successMessage: 'Je account is succesvol aangemaakt als', successDesktopHint: 'Klik op de onderstaande knop om terug te keren naar de desktop-app.', returnToDesktop: 'Terug naar Clipop Agent', desktopNotOpened: 'Als de desktop-app niet automatisch opent, zorg er dan voor dat Clipop Agent draait.'",
    dashboardNew: "untitled: 'Naamloos', clip: 'Clip', clipsCount: 'hoogtepunten', clipsHint: 'Klik op een clip om af te spelen', desktopLoginDetected: 'Desktop-app Login Gedetecteerd', desktopLoginHint: 'Klik op de onderstaande knop om terug te keren naar Clipop Agent', returnToDesktop: 'Terug naar Clipop Agent', welcomeBack: 'Welkom terug', videosProcessed: 'Verwerkte Video\'s', videosProcessedDesc: 'Totaal verwerkte video\'s', clipsGenerated: 'Gegenereerde Clips', clipsGeneratedDesc: 'Totaal hoogtepuntclips', currentPlan: 'Huidig Abonnement', upgradePlan: 'Abonnement Upgraden', processNewVideo: 'Nieuwe Video Verwerken', feedback: 'Feedback', historyHint: 'Klik op voltooide records om uit te vouwen en hoogtepuntclips te bekijken', processNewVideoDesc: 'Ga naar de homepage om een nieuwe lange video te verwerken', goToProcessor: 'Ga naar Videoprocessor', userFeedback: 'Gebruikersfeedback', feedbackDesc: 'Vertel ons over functies die je wilt verbeteren of problemen die je bent tegengekomen', feedbackPlaceholder: 'Voer je feedback in (suggesties, bugs, functieverzoeken enz.)', feedbackSubmitted: 'Ingediend, bedankt voor je feedback!', submitFeedback: 'Feedback Indienen', feedbackFailed: 'Feedback indienen mislukt', statusPending: 'In afwachting', statusProcessing: 'Verwerken', statusCompleted: '✓ Voltooid', statusFailed: 'Mislukt'",
    blogNew: "subtitle: 'Laatste nieuws, tips en updates van Clipop AI', views: 'weergaven'",
  },
  no: {
    navAdd: "download: 'Last Ned App', light: 'Lys', dark: 'Mørk'",
    commonNew: "error: 'Feil', ready: 'Klar', failed: 'Mislyktes', saving: 'Lagrer...', score: 'Poeng', user: 'Bruker'",
    footer: "desc: 'Forvandle dine lange videoer til fengende korte klipp med AI-drevet analyse og redigering.', quickLinks: 'Hurtiglenker', legal: 'Juridisk', privacy: 'Personvernregler', terms: 'Tjenestevilkår', contact: 'Kontakt', rights: 'Alle rettigheter reservert.'",
    heroBadge: "badge: 'AI-drevet Videobehandling',",
    howItWorks: "howItWorks: { title: 'Slik Fungerer Det', step1: { title: 'Videoinndata', desc: 'Lim inn URL eller last opp videoen din' }, step2: { title: 'AI-analyse', desc: 'AI oppdager automatisk høydepunkter' }, step3: { title: 'Lag Klipp', desc: 'Korte videoer opprettes' }, step4: { title: 'Last Ned', desc: 'Eksporter og del overalt' } },",
    videoNew: "creditsAvailable: 'kreditter tilgjengelig', signInToStart: 'for å starte videobehandling', pasteUrlPlaceholder: 'Lim inn en video-URL (MP4, MOV, AVI...)', useLocalAgent: 'Bruk lokal Mac Agent (anbefalt for stabil YouTube)', uploadLocal: 'Last opp en lokal videofil (anbefalt når YouTube-lenke er blokkert)', selectedFile: 'Valgt', downloadMacApp: 'Last Ned Mac App', viewPricing: 'Se Priser', clipsReady: 'klipp klare', playableClips: 'avspillbare klipp', failedClips: 'mislyktes', aiFinished: 'AI har fullført utvelgelsen av de sterkeste øyeblikkene fra kildevideoen din.', openToPreview: 'Åpne et hvilket som helst klart klipp for forhåndsvisning, eller last ned MP4 direkte.', clipsBeingGenerated: 'Klipp genereres:', videoPreviewNotAvailable: 'Videoforhåndsvisning ikke tilgjengelig', clipMayStillProcessing: 'Klippet behandles kanskje fortsatt eller genereringen mislyktes.', insufficientCredits: 'Utilstrekkelige kreditter. Du trenger minst 30 kreditter.', enterVideoUrl: 'Vennligst skriv inn en video-URL eller last opp en lokal videofil.', enterValidUrl: 'Vennligst skriv inn en gyldig offentlig http(s) video-URL.'",
    videoStage: "stage: { init: 'Initialiserer...', extractFrames: 'Ekstraherer videobilder...', framesExtracted: 'Bilder ekstrahert vellykket', framesUnavailable: 'Fortsetter med analyse', aiAnalysis: 'AI analyserer videoinnhold...', analysisComplete: 'Analyse fullført', generatingClip: 'Oppretter høydepunktsklipp...', clipReady: 'Høydepunktsklipp klart', saving: 'Lagrer resultater...', complete: 'Behandling fullført!', error: 'Feil oppstod' },",
    pricingNew: "paymentNote: 'Alipay for Kina · Creem for Internasjonalt (Visa / Mastercard / Apple Pay / Google Pay)', secureNote: 'Alle betalinger sikret med TLS 256-bit kryptering', faqTitle: 'Ofte Stilte Spørsmål', faq: { q1: 'Hva er en kreditt?', a1: 'Hver kreditt representerer behandlingskraft. Behandling av et videoklipp koster 30 kreditter.', q2: 'Hvordan fungerer daglig kreditt-nullstilling?', a2: 'Kreditter nullstilles til planens daglige grense kl. 00:00 UTC hver dag. Ubrukte kreditter overføres ikke.', q3: 'Kan jeg oppgradere eller nedgradere planen min?', a3: 'Ja, du kan endre planen din når som helst. Endringer trer i kraft umiddelbart.', q4: 'Hvilke videokilder støttes?', a4: 'Vi støtter YouTube, Bilibili og direkte videofil-opplasting (MP4, MOV, AVI).', q5: 'Hvilke betalingsmetoder støttes?', a5: 'Alipay for Kina-brukere, Creem (Visa, Mastercard, Apple Pay, Google Pay) for internasjonale brukere.' }, mostPopular: 'Mest Populære'",
    downloadPage: "downloadPage: { title: 'Last Ned Clipop Agent', subtitle: 'Skrivebordsapp for stabil YouTube/Bilibili videobehandling', badge: 'Skrivebordsapp', macTitle: 'macOS', macDesc: 'For Apple Silicon (M1/M2/M3/M4) Mac-er', downloadButton: 'Last Ned for macOS', version: 'Versjon', fileSize: 'Filstørrelse', requirements: 'macOS 12.0 eller senere', installing: 'Installasjonsguide', step1: 'Klikk på nedlastingsknappen for å lagre .dmg-filen', step2: 'Dobbeltklikk på den nedlastede .dmg-filen', step3: 'Dra Clipop Agent til Programmer-mappen', step4: 'Åpne Clipop Agent fra Programmer', notAvailable: 'Nedlasting forberedes, vennligst sjekk senere', backToHome: 'Tilbake til Hjem', whyDesktopTitle: 'Hvorfor Bruke Skrivebordsappen?', features: { stable: { title: 'Stabil Behandling', desc: 'Behandle videoer lokalt med maksimal stabilitet' }, fast: { title: 'Rask Nedlasting', desc: 'Last ned videoer direkte uten nettleserbegrensninger' }, local: { title: 'Lokal Behandling', desc: 'Behandle videoer på din Mac for personvern og hastighet' } } },",
    loginNew: "successTitle: 'Innlogging Vellykket!', successMessage: 'Du er logget inn som', successDesktopHint: 'Klikk på knappen nedenfor for å gå tilbake til skrivebordsappen.', returnToDesktop: 'Tilbake til Clipop Agent', desktopNotOpened: 'Hvis skrivebordsappen ikke åpner automatisk, vennligst sørg for at Clipop Agent kjører.'",
    registerNew: "errorNameRequired: 'Vennligst skriv inn navnet ditt', errorEmailRequired: 'Vennligst skriv inn e-posten din', errorPasswordLength: 'Passordet må være minst 6 tegn', errorPasswordMismatch: 'Passordene samsvarer ikke', errorEmailExists: 'Denne e-posten er allerede registrert. Vennligst logg inn.', errorSendCode: 'Kunne ikke sende kode', errorNetwork: 'Nettverksfeil. Vennligst prøv igjen.', errorCodeLength: 'Vennligst skriv inn 6-sifret kode', successTitle: 'Konto Opprettet!', successMessage: 'Kontoen din er opprettet som', successDesktopHint: 'Klikk på knappen nedenfor for å gå tilbake til skrivebordsappen.', returnToDesktop: 'Tilbake til Clipop Agent', desktopNotOpened: 'Hvis skrivebordsappen ikke åpner automatisk, vennligst sørg for at Clipop Agent kjører.'",
    dashboardNew: "untitled: 'Uten tittel', clip: 'Klipp', clipsCount: 'høydepunkter', clipsHint: 'Klikk på et klipp for å spille av', desktopLoginDetected: 'Skrivebordsapp-innlogging Oppdaget', desktopLoginHint: 'Klikk på knappen nedenfor for å gå tilbake til Clipop Agent', returnToDesktop: 'Tilbake til Clipop Agent', welcomeBack: 'Velkommen tilbake', videosProcessed: 'Behandlede Videoer', videosProcessedDesc: 'Totalt behandlede videoer', clipsGenerated: 'Genererte Klipp', clipsGeneratedDesc: 'Totalt høydepunktsklipp', currentPlan: 'Nåværende Plan', upgradePlan: 'Oppgrader Plan', processNewVideo: 'Behandl Ny Video', feedback: 'Tilbakemelding', historyHint: 'Klikk på fullførte poster for å utvide og se høydepunktsklipp', processNewVideoDesc: 'Gå til hjemmesiden for å behandle en ny lang video', goToProcessor: 'Gå til Videoprosessor', userFeedback: 'Brukertilbakemelding', feedbackDesc: 'Fortell oss om funksjoner du vil forbedre eller problemer du har møtt', feedbackPlaceholder: 'Skriv inn tilbakemeldingen din (forslag, feil, funksjonsforespørsler osv.)', feedbackSubmitted: 'Innsendt, takk for tilbakemeldingen!', submitFeedback: 'Send Inn Tilbakemelding', feedbackFailed: 'Kunne ikke sende inn tilbakemelding', statusPending: 'Venter', statusProcessing: 'Behandler', statusCompleted: '✓ Fullført', statusFailed: 'Mislyktes'",
    blogNew: "subtitle: 'Siste nytt, tips og oppdateringer fra Clipop AI', views: 'visninger'",
  },
  sv: {
    navAdd: "download: 'Ladd Ner App', light: 'Ljus', dark: 'Mörk'",
    commonNew: "error: 'Fel', ready: 'Redo', failed: 'Misslyckades', saving: 'Sparar...', score: 'Poäng', user: 'Användare'",
    footer: "desc: 'Förvandla dina långa videor till fängande korta klipp med AI-driven analys och redigering.', quickLinks: 'Snabblänkar', legal: 'Juridiskt', privacy: 'Integritetspolicy', terms: 'Tjänstevillkor', contact: 'Kontakt', rights: 'Alla rättigheter förbehållna.'",
    heroBadge: "badge: 'AI-driven Videobearbetning',",
    howItWorks: "howItWorks: { title: 'Så Här Fungerar Det', step1: { title: 'Mata In Video', desc: 'Klistra in URL eller ladda upp din video' }, step2: { title: 'AI-analys', desc: 'AI upptäcker automatiskt höjdpunkter' }, step3: { title: 'Skapa Klipp', desc: 'Korta videor skapas' }, step4: { title: 'Ladda Ner', desc: 'Exportera och dela var som helst' } },",
    videoNew: "creditsAvailable: 'krediter tillgängliga', signInToStart: 'för att börja bearbeta videor', pasteUrlPlaceholder: 'Klistra in en video-URL (MP4, MOV, AVI...)', useLocalAgent: 'Använd lokal Mac Agent (rekommenderas för stabil YouTube)', uploadLocal: 'Ladda upp en lokal videofil (rekommenderas när YouTube-länk är blockerad)', selectedFile: 'Vald', downloadMacApp: 'Ladda Ner Mac App', viewPricing: 'Se Priser', clipsReady: 'klipp redo', playableClips: 'spelbara klipp', failedClips: 'misslyckades', aiFinished: 'AI har slutfört urvalet av de starkaste ögonblicken från din källvideo.', openToPreview: 'Öppna ett redo klipp för förhandsgranskning, eller ladda ner MP4 direkt.', clipsBeingGenerated: 'Klipp genereras:', videoPreviewNotAvailable: 'Videoförhandsgranskning inte tillgänglig', clipMayStillProcessing: 'Klippet bearbetas fortfarande eller genereringen misslyckades.', insufficientCredits: 'Otillräckliga krediter. Du behöver minst 30 krediter.', enterVideoUrl: 'Vänligen ange en video-URL eller ladda upp en lokal videofil.', enterValidUrl: 'Vänligen ange en giltig offentlig http(s) video-URL.'",
    videoStage: "stage: { init: 'Initierar...', extractFrames: 'Extraherar videobildrutor...', framesExtracted: 'Bildrutor extraherade framgångsrikt', framesUnavailable: 'Fortsätter med analys', aiAnalysis: 'AI analyserar videoinnehåll...', analysisComplete: 'Analys slutförd', generatingClip: 'Skapar höjdpunktsklipp...', clipReady: 'Höjdpunktsklipp redo', saving: 'Sparar resultat...', complete: 'Bearbetning slutförd!', error: 'Fel uppstod' },",
    pricingNew: "paymentNote: 'Alipay för Kina · Creem för Internationellt (Visa / Mastercard / Apple Pay / Google Pay)', secureNote: 'Alla betalningar säkrade med TLS 256-bit kryptering', faqTitle: 'Vanliga Frågor', faq: { q1: 'Vad är en kredit?', a1: 'Varje kredit representerar bearbetningskraft. Att bearbeta ett videoklipp kostar 30 krediter.', q2: 'Hur fungerar daglig kredit-återställning?', a2: 'Krediter återställs till din plans dagliga gräns kl. 00:00 UTC varje dag. Oanvända krediter överförs inte.', q3: 'Kan jag uppgradera eller nedgradera min plan?', a3: 'Ja, du kan ändra din plan när som helst. Ändringar träder i kraft omedelbart.', q4: 'Vilka videokällor stöds?', a4: 'Vi stöder YouTube, Bilibili och direkta videofiluppladdningar (MP4, MOV, AVI).', q5: 'Vilka betalningsmetoder stöds?', a5: 'Alipay för Kina-användare, Creem (Visa, Mastercard, Apple Pay, Google Pay) för internationella användare.' }, mostPopular: 'Mest Populära'",
    downloadPage: "downloadPage: { title: 'Ladda Ner Clipop Agent', subtitle: 'Skrivbordsapp för stabil YouTube/Bilibili videobearbetning', badge: 'Skrivbordsapp', macTitle: 'macOS', macDesc: 'För Apple Silicon (M1/M2/M3/M4) Mac-datorer', downloadButton: 'Ladda Ner för macOS', version: 'Version', fileSize: 'Filstorlek', requirements: 'macOS 12.0 eller senare', installing: 'Installationsguide', step1: 'Klicka på nedladdningsknappen för att spara .dmg-filen', step2: 'Dubbelklicka på den nedladdade .dmg-filen', step3: 'Dra Clipop Agent till Program-mappen', step4: 'Öppna Clipop Agent från Program', notAvailable: 'Nedladdning förbereds, vänligen kontrollera senare', backToHome: 'Tillbaka till Hem', whyDesktopTitle: 'Varför Använda Skrivbordsappen?', features: { stable: { title: 'Stabil Bearbetning', desc: 'Bearbeta videor lokalt med maximal stabilitet' }, fast: { title: 'Snabb Nedladdning', desc: 'Ladda ner videor direkt utan webbläsarbegränsningar' }, local: { title: 'Lokal Bearbetning', desc: 'Bearbeta videor på din Mac för integritet och hastighet' } } },",
    loginNew: "successTitle: 'Inloggning Lyckades!', successMessage: 'Du har loggat in som', successDesktopHint: 'Klicka på knappen nedan för att återvända till skrivbordsappen.', returnToDesktop: 'Återvänd till Clipop Agent', desktopNotOpened: 'Om skrivbordsappen inte öppnas automatiskt, vänligen säkerställ att Clipop Agent körs.'",
    registerNew: "errorNameRequired: 'Vänligen ange ditt namn', errorEmailRequired: 'Vänligen ange din e-post', errorPasswordLength: 'Lösenordet måste vara minst 6 tecken', errorPasswordMismatch: 'Lösenorden matchar inte', errorEmailExists: 'Denna e-post är redan registrerad. Vänligen logga in istället.', errorSendCode: 'Kunde inte skicka kod', errorNetwork: 'Nätverksfel. Vänligen försök igen.', errorCodeLength: 'Vänligen ange 6-siffrig kod', successTitle: 'Konto Skapat!', successMessage: 'Ditt konto har skapats som', successDesktopHint: 'Klicka på knappen nedan för att återvända till skrivbordsappen.', returnToDesktop: 'Återvänd till Clipop Agent', desktopNotOpened: 'Om skrivbordsappen inte öppnas automatiskt, vänligen säkerställ att Clipop Agent körs.'",
    dashboardNew: "untitled: 'Namnlös', clip: 'Klipp', clipsCount: 'höjdpunkter', clipsHint: 'Klicka på ett klipp för att spela upp', desktopLoginDetected: 'Skrivbordsapp-inloggning Upptäckt', desktopLoginHint: 'Klicka på knappen nedan för att återvända till Clipop Agent', returnToDesktop: 'Återvänd till Clipop Agent', welcomeBack: 'Välkommen tillbaka', videosProcessed: 'Bearbetade Videor', videosProcessedDesc: 'Totalt bearbetade videor', clipsGenerated: 'Genererade Klipp', clipsGeneratedDesc: 'Totalt höjdpunktsklipp', currentPlan: 'Nuvarande Plan', upgradePlan: 'Uppgradera Plan', processNewVideo: 'Bearbeta Ny Video', feedback: 'Feedback', historyHint: 'Klicka på slutförda poster för att expandera och visa höjdpunktsklipp', processNewVideoDesc: 'Gå till startsidan för att bearbeta en ny lång video', goToProcessor: 'Gå till Videoprocessor', userFeedback: 'Användarfeedback', feedbackDesc: 'Berätta om funktioner du vill förbättra eller problem du har stött på', feedbackPlaceholder: 'Ange din feedback (förslag, buggar, funktionsförfrågningar etc.)', feedbackSubmitted: 'Inskickat, tack för din feedback!', submitFeedback: 'Skicka In Feedback', feedbackFailed: 'Kunde inte skicka in feedback', statusPending: 'Väntande', statusProcessing: 'Bearbetar', statusCompleted: '✓ Slutförd', statusFailed: 'Misslyckades'",
    blogNew: "subtitle: 'Senaste nytt, tips och uppdateringar från Clipop AI', views: 'visningar'",
  },
};

function processLang(lang, t) {
  const langPattern = new RegExp(`(\\s+${lang}: flattenTranslations\\(\\{\\n    \\.\.\.commonTranslations,\\n    nav: \\{\\n      [^}]+),\\n    \\}`, 's');
  
  const match = content.match(langPattern);
  if (!match) {
    console.log(`Could not find pattern for ${lang}`);
    return false;
  }
  
  const oldNav = match[1];
  const newNav = oldNav + `, ${t.navAdd}\n    }`;
  content = content.replace(oldNav + ',\n    }', newNav);

  // Add common new keys after nav
  content = content.replace(
    new RegExp(`(\\s+${lang}: flattenTranslations\\(\\{[\\s\\S]*?nav: \\{[^}]+\\},)`),
    `$1\n    common: {\n      ${t.commonNew},\n      loading: content.match(/loading:/)?.[0] || '',\n    },`
  );

  console.log(`Processed ${lang} - nav updated`);
  return true;
}

// Process each language
for (const [lang, t] of Object.entries(translations)) {
  processLang(lang, t);
}

fs.writeFileSync(filePath, content, 'utf8');
console.log('Done!');
